routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\{
  PagesController,
  TransactionController,
  BlogController,
  KelasController,
  AuthController
};
use App\Http\Controllers\Cp\{
  DashboardController,
  PostController,
  UserController,
  SettingController,
  TransaksiController,
  ClassController,
  ReportController,
  MateriController
};
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// landing or homepage
Route::get('/' , [PagesController::class, 'index']);
// set class list & detail
Route::get('/kelas' , [KelasController::class, 'index']);
Route::get('/materi-kelas/{id}' , [KelasController::class, 'materi_kelas'])->name('materi.kelas');
Route::get('/mulai-kelas/{kelas_id}/video-materi/{id}' , [KelasController::class, 'mulai_kelas'])->name('materi.play');
// detail blog & show all blog
Route::get('/blog' , [BlogController::class, 'index']);
Route::get('/blog-detail/{slug}' , [BlogController::class, 'blog_detail'])->name('blog-detail');
// class transaction
Route::get('/transaksi-kelas/{slug}' , [TransactionController::class, 'index']);
Route::post('/transaksi-kelas' , [TransactionController::class, 'transaction'])->name('transcation.class');
// about
Route::get('/tentang-kami', [PagesController::class, 'about']);
// login & register-user
Route::get('/login' , [AuthController::class, 'login'])->name('login');
Route::post('/login' , [AuthController::class, 'process_login']);
Route::get('/register' , [AuthController::class, 'register']);
Route::post('/register' , [AuthController::class, 'process_register']);
// success
Route::get('/success' , [TransactionController::class, 'success'])->name('transaction.success');

Route::group(['prefix' => 'site', 'middleware' => 'auth'], function(){
  // set profile user
      Route::get('/profil' , [UserController::class, 'profil']);
      Route::post('/profil' , [UserController::class, 'update_profil']);
  Route::group(['mid dleware' => ['role.check:admin']], function(){
      Route::get('admin', [DashboardController::class, 'index']);
      // post
      Route::resource('admin/posts', PostController::class);
      // setting
      Route::get('admin/setting/1', [SettingController::class,'index']);
      Route::put('admin/setting/{id}', [SettingController::class,'update'])->name('setting.update');
      // user
      Route::get('admin/users', [UserController::class,'index']);
      Route::get('admin/users/create', [UserController::class,'create']);
      Route::get('admin/users/edit/{id}', [UserController::class, 'edit']);
      Route::put('admin/users/update/{id}', [UserController::class, 'update']);
      // kelas
      Route::resource('admin/kelas', ClassController::class);
      // materi
      Route::get('admin/materi-kelas', [MateriController::class,'index'])->name('materi.index');
      Route::get('admin/materi-kelas/create', [MateriController::class,'create'])->name('materi.create');
      Route::post('admin/materi-kelas', [MateriController::class,'store'])->name('materi.store');
      Route::get('admin/materi-kelas/edit/{id}', [MateriController::class,'edit'])->name('materi.edit');
      Route::put('admin/materi-kelas/update/{id}', [MateriController::class,'update'])->name('materi.update');
      Route::delete('admin/materi-kelas/{id}', [MateriController::class,'destroy'])->name('materi.destroy');
      // transaksi
      Route::get('admin/transaksi', [TransaksiController::class, 'index']);
      Route::get('/transaksi-kelas/{id}/setstatus' , [TransaksiController::class, 'setStatus'])->name('transcation.status');
      Route::get('/transaksi-kelas/detail/{id}' , [TransaksiController::class, 'detail'])->name('transcation.detail');
      // Report
      Route::get('admin/report', [ReportController::class, 'index']);
      Route::get('admin/report/user', [ReportController::class, 'user']);
      Route::get('admin/report/transaksi', [ReportController::class, 'transaksi']);
      Route::get('admin/report/kelas', [ReportController::class, 'kelas']);
      // manually report
      Route::get('admin/report/kelas/print', [ReportController::class, 'printkelas']);
      Route::get('admin/report/transaksi/print', [ReportController::class, 'printtransaction']);
      Route::get('admin/report/user/print', [ReportController::class, 'printuser']);
  });
  // set logout
  Route::post('logout', [AuthController::class, 'logout'])->name('admin.logout');
});

resources/views/admin_layout/view_stucture.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <!--To prevent most search engine web crawlers from indexing a page on your site-->
    <link rel="icon" href="{{asset('assets/images/logo.svg')}}" type="image/png" sizes="16x16"> 
    <meta name="robots" content="noindex">
    <meta name="googlebot" content="noindex">

    <title>{{$title}}</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!-- General CSS Files -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
        integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <!-- Template CSS -->
    <link rel="stylesheet" href="{{asset('Backend/css/style.css')}}">
    <link rel="stylesheet" href="{{asset('Backend/css/components.css')}}">
    <link rel="stylesheet" href="{{asset('Backend/css/custom.css')}}">
    <link rel="stylesheet" type="text/css"
        href="https://cdn.datatables.net/v/bs4/dt-1.10.22/b-1.6.4/b-html5-1.6.4/r-2.2.6/datatables.min.css" />

    <link rel="stylesheet" type="text/css"
        href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css" />
    <link rel="stylesheet" type="text/css"
        href="https://cdn.datatables.net/buttons/1.6.4/css/buttons.bootstrap4.min.css" />

   

    {{-- @stack('style') --}}
</head>

<body>
    <div id="app">
        <div class="main-wrapper main-wrapper-1">
            <div class="navbar-bg"></div>
            <nav class="navbar navbar-expand-lg main-navbar">
                <form class="form-inline mr-auto">
                    <ul class="navbar-nav mr-3">
                        <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i
                                    class="fas fa-bars"></i></a></li>
                        <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i
                                    class="fas fa-search"></i></a></li>
                    </ul>
                </form>
                <ul class="navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                            <img alt="image" src="{{asset('Backend/img/avatar.png')}}" class="rounded-circle mr-1">
                        <div class="d-sm-none d-lg-inline-block">{{Auth::user()->name}}</div>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                             <a href="{{url('/site/admin/users/edit/'.Crypt::Encrypt(Auth::user()->id))}}" class="dropdown-item has-icon">
                                <i class="far fa-user"></i> Profile
                            </a>
                            <div class="dropdown-divider"></div>
                        <form action="{{route('admin.logout')}}" method="POST">
                            @csrf
                                <button class="dropdown-item has-icon text-danger"><i class="fas mt-2 fa-sign-out-alt"></i> Logout</button>
                            </form>
                  
                            <form id="logout-form" action="#" method="POST" style="display: none;">

                            </form>
                        </div>
                    </li>
                </ul>
            </nav>
            <div class="main-sidebar">
                <aside id="sidebar-wrapper">
                    <div class="sidebar-brand">
                        <a href="{{url('site/admin')}}"><strong>TemanBelajar</strong></a>
                    </div>
                    <div class="sidebar-brand sidebar-brand-sm">
                        <a href="#">TB</a>
                    </div>
                    <ul class="sidebar-menu">
                        <li class="menu-header">Dashboard</li>
                        <li class="#">
                            <a class="nav-link" href="{{url('site/admin')}}">
                                <i class="fas fa-fire"></i><span>Dashboard</span>
                            </a>
                        </li>
                        <li class="menu-header">Konten</li>
                        <li class="#">
                            <a class="nav-link" href="{{route('posts.index')}}">
                                <i class="fas fa-newspaper"></i> <span>Blog</span>
                            </a>
                        </li>
                        <li class="menu-header">Media</li>
                        <li class="#">
                            <a class="nav-link" href="{{url('site/admin/kelas')}}">
                                <i class="far fa-paper-plane"></i> <span>Kelas</span>
                            </a>
                        </li>
                        <li class="#">
                            <a class="nav-link" href="{{url('site/admin/materi-kelas')}}">
                                <i class="fas fa-play-circle"></i> <span>Materi Kelas</span>
                            </a>
                        </li>
                        <li class="menu-header">Transaksi</li>
                        <li class="#">
                            <a class="nav-link" href="{{url('site/admin/transaksi')}}">
                                <i class="fas fa-print"></i> <span>Transaksi Masuk</span>
                            </a>
                        </li>
                        <li class="menu-header">Laporan</li>
                        <li class="#">
                            <a class="nav-link" href="{{url('site/admin/report')}}">
                                <i class="fas fa-database"></i> <span>Laporan</span>
                            </a>
                        </li>
                        <li class="menu-header">Konfigurasi</li>
                        <li class="#">
                            <a class="nav-link" href="{{url('site/admin/users')}}">
                                <i class="fas fa-users"></i> <span>User</span>
                            </a>
                        </li>
                        <li class="#">
                            <a class="nav-link" href="{{url('site/admin/setting/1')}}">
                                <i class="fas fa-cog"></i> <span>Pengaturan</span>
                            </a>
                        </li>
                    </ul>
                </aside>
            </div>
            @yield('Content')
            <footer class="main-footer">
                <div class="footer-left">
                    Copyright &copy; 2020
                    <div class="bullet"></div> <a href="#">Muhamad Zainal Arifin</a>
                </div>
            </footer>
        </div>
    </div>

    <!-- General JS Scripts -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
    <script src="{{asset('Backend/js/stisla.js')}}"></script>
    <script src="{{asset('Backend/js/scripts.js')}}"></script>
    <script src="{{asset('Backend/js/ckeditor.js')}}"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.4/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.4/js/buttons.bootstrap4.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.4/js/buttons.flash.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.4/js/buttons.html5.min.js"></script>
    <script type="text/javascript"
        src="https://cdn.datatables.net/v/bs4/dt-1.10.22/b-1.6.4/b-html5-1.6.4/r-2.2.6/datatables.min.js"></script>
    <script>
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

    </script>
    <script>
        $('.js-upload-image').change(function (event) {
            makePreview(this);
            $('#upload-img-preview').show();
            $('#upload-img-delete').show();
        });

        function makePreview(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#upload-img-preview').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        $('#upload-img-delete').click(function (event) {
            event.preventDefault();

            $('#upload-img-preview').attr('src', '').hide();
            $('.custom-file-input').val(null);
            $(this).hide();
        });


        if ($('#description').length != 0) {
            CKEDITOR.replace('description', config);
        }

       $(document).ready(function () {
            $('#TABLE_USER').DataTable();
        });
       $(document).ready(function () {
            $('#TABLE_TRANSAKSI').DataTable();
        });
        $(document).ready(function () {
            $('#TABLE_POST').DataTable();
        });
        $(document).ready(function () {
            $('#TABLE_KELAS').DataTable();
        });
        // report
        $(document).ready(function () {
            $('#TABLE_USER_2').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    'excel', 'pdf','csv'
                ]
             }  
            );
        });
       $(document).ready(function () {
            $('#TABLE_TRANSAKSI_2').DataTable({ 
                dom: 'Bfrtip',
                buttons: [
                    'excel', 'pdf','csv'
                ]  
            });
        });
        $(document).ready(function ({}) {
            $('#TABLE_POST_2').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    'excel', 'pdf','csv'
                ] 
            });
        });
        $(document).ready(function () {
            $('#TABLE_KELAS_2').DataTable({
                    dom: 'Bfrtip',
                    buttons: [
                        'excel', 'pdf','csv'
                    ]
            });
        });
    </script>
</body>
</html>