routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\{
  PagesController,
  TransactionController,
  BlogController,
  KelasController,
  AuthController
};
use App\Http\Controllers\Cp\{
  DashboardController,
  PostController,
  UserController,
  SettingController,
  TransaksiController,
  ClassController,
  ReportController,
  MateriController
};
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// landing or homepage
Route::get('/' , [PagesController::class, 'index']);
// set class list & detail
Route::get('/kelas' , [KelasController::class, 'index']);
Route::get('/materi-kelas/{id}' , [KelasController::class, 'materi_kelas'])->name('materi.kelas');
Route::get('/mulai-kelas/{kelas_id}/video-materi/{id}' , [KelasController::class, 'mulai_kelas'])->name('materi.play');
// detail blog & show all blog
Route::get('/blog' , [BlogController::class, 'index']);
Route::get('/blog-detail/{slug}' , [BlogController::class, 'blog_detail'])->name('blog-detail');
// class transaction
Route::get('/transaksi-kelas/{slug}' , [TransactionController::class, 'index']);
Route::post('/transaksi-kelas' , [TransactionController::class, 'transaction'])->name('transcation.class');
// about
Route::get('/tentang-kami', [PagesController::class, 'about']);
// login & register-user
Route::get('/login' , [AuthController::class, 'login'])->name('login');
Route::post('/login' , [AuthController::class, 'process_login']);
Route::get('/register' , [AuthController::class, 'register']);
Route::post('/register' , [AuthController::class, 'process_register']);
// success
Route::get('/success' , [TransactionController::class, 'success'])->name('transaction.success');

Route::group(['prefix' => 'site', 'middleware' => 'auth'], function(){
  // set profile user
      Route::get('/profil' , [UserController::class, 'profil']);
      Route::post('/profil' , [UserController::class, 'update_profil']);
  Route::group(['mid dleware' => ['role.check:admin']], function(){
      Route::get('admin', [DashboardController::class, 'index']);
      // post
      Route::resource('admin/posts', PostController::class);
      // setting
      Route::get('admin/setting/1', [SettingController::class,'index']);
      Route::put('admin/setting/{id}', [SettingController::class,'update'])->name('setting.update');
      // user
      Route::get('admin/users', [UserController::class,'index']);
      Route::get('admin/users/create', [UserController::class,'create']);
      Route::get('admin/users/edit/{id}', [UserController::class, 'edit']);
      Route::put('admin/users/update/{id}', [UserController::class, 'update']);
      // kelas
      Route::resource('admin/kelas', ClassController::class);
      // materi
      Route::get('admin/materi-kelas', [MateriController::class,'index'])->name('materi.index');
      Route::get('admin/materi-kelas/create', [MateriController::class,'create'])->name('materi.create');
      Route::post('admin/materi-kelas', [MateriController::class,'store'])->name('materi.store');
      Route::get('admin/materi-kelas/edit/{id}', [MateriController::class,'edit'])->name('materi.edit');
      Route::put('admin/materi-kelas/update/{id}', [MateriController::class,'update'])->name('materi.update');
      Route::delete('admin/materi-kelas/{id}', [MateriController::class,'destroy'])->name('materi.destroy');
      // transaksi
      Route::get('admin/transaksi', [TransaksiController::class, 'index']);
      Route::get('/transaksi-kelas/{id}/setstatus' , [TransaksiController::class, 'setStatus'])->name('transcation.status');
      Route::get('/transaksi-kelas/detail/{id}' , [TransaksiController::class, 'detail'])->name('transcation.detail');
      // Report
      Route::get('admin/report', [ReportController::class, 'index']);
      Route::get('admin/report/user', [ReportController::class, 'user']);
      Route::get('admin/report/transaksi', [ReportController::class, 'transaksi']);
      Route::get('admin/report/kelas', [ReportController::class, 'kelas']);
      // manually report
      Route::get('admin/report/kelas/print', [ReportController::class, 'printkelas']);
      Route::get('admin/report/transaksi/print', [ReportController::class, 'printtransaction']);
      Route::get('admin/report/user/print', [ReportController::class, 'printuser']);
  });
  // set logout
  Route::post('logout', [AuthController::class, 'logout'])->name('admin.logout');
});

app/Http/Controllers/Cp/PostController.php
<?php

namespace App\Http\Controllers\Cp;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Crypt;
use App\Models\blog;
use Illuminate\Support\Str;

class PostController extends Controller
{
    public function index()
    {
        $this->var = [
            'title' => 'Admin - Post',
            'post' => blog::all()
        ];
        return view('admin.Post.index', $this->var);
    }

    public function create()
    {
        $this->var = [
            'title' => 'Admin - Post-Add'
        ];
        return view('admin.Post.create', $this->var);
    }


    public function store(Request $req)
    {
        $req->validate([
            'title' => 'required|min:4|max:255',
            'isi' => 'required',
            'thumbnail' => 'image|mimes:jpg,png,jpeg|max:2048'
        ]);
        $file = $req->file('thumbnail');
        $thumbnail = $file->move('images/posts/', time(). '-' . Str::limit(Str::slug($req->title), 50, '').'-'.strtotime('now').'.'.$file->getClientOriginalExtension());
        blog::create([
            'title' => $req->title,
            'author' => $req->author,
            'isi' => $req->isi,
            'thumbnail' => $thumbnail,
            'status' => $req->status,
            'slug' => Str::slug($req->title),
        ]);
        return redirect()->route('posts.index')->with('status', 'Data Post Berhasil Ditambahkan ke Database');
        // store data to database
    }

    public function edit($id)
    {
        $dec = Crypt::Decrypt($id);
        $this->var = [
            'title' => 'Admin -Post-Edit',
            'post' => blog::findOrfail($dec)
        ];
        
        return view('admin.Post.edit', $this->var);
        // show from edit post
    }

    public function update(Request $req, $id)
    {
        $req->validate([
            'title' => 'required|min:4|max:255',
            'isi' => 'required',
            'thumbnail' => 'image|mimes:jpg,png,jpeg|max:2048'
        ]);

        $blog =  blog::findOrfail($id);
        if($req->hasFile('thumbnail')){
            if(file_exists($blog->thumbnail)){
                unlink($blog->thumbnail);
            }
            $file = $req->file('thumbnail');
            $image = $file->move('images/posts/', time(). '-'. Str::limit(Str::slug($req->title), 50, ''). '-' . strtotime('now'). '.'. $file->getClientOriginalExtension() );
        }
        blog::where(['id' => $id])->update([
            'title' => $req->title,
            'author' => $req->author,
            'isi' => $req->isi,
            'thumbnail' => !empty($image) ? $image : $blog->thumbnail,
            'status' => $req->status,
            'slug' => Str::slug($req->title),
        ]);
        return redirect()->route('posts.index')->with('status', 'Data Post Berhasil Diubah dari Database');
        // update data  post
    }

    public function destroy($id)
    {
    
        $blog = blog::findOrfail($id);
        if(file_exists($blog->thumbnail)){
            unlink($blog->thumbnail);
            $blog->delete();
            return redirect()->back()->with('status', 'Data Post Berhasil Dihapus dari Database');
        }
        // delete data post
    }
}

resources/views/admin/Post/create.blade.php
@extends('admin_layout.view_stucture')
@section('Content')
     <!-- Main Content -->
     <div class="main-content">
      <section class="section">
          <div class="section-header">
              <h1>Tambah Postingan</h1>
          </div>
            <form action="{{route('posts.store')}}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-8">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="text-black-50">Posts</h4>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type="text" id="title" class="form-control @error('title') is-invalid @enderror" name="title"  autofocus="" value="">
                                @error('title')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="title">Author</label>
                                <input type="text" id="title" class="form-control @error('author') is-invalid @enderror" name="author"  autofocus="" value="{{Auth::user()->name}}">
                                @error('author')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="title">Status</label>
                                <select name="status" id="" class="form-control" required>
                                    <option value="" class="form-control">-Pilih Kategori-</option>
                                    <option value="Publish" class="form-control">Publish</option>>
                                    <option value="Draft" class="form-control">Draft</option>>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="description">isi</label>
                                <textarea id="isi" cols="30" rows="10" class="form-control @error('isi') is-invalid @enderror" style="height: auto;" name="isi"></textarea>
                                @error('isi')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-4">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="text-black-50">Meta data</h4>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label>Gambar</label>
                                <div class="mb-2">
                                    <img src="" class="img-fluid" alt="" id="upload-img-preview" style="display: none;">
                                    <a href="#" class="text-danger" id="upload-img-delete" style="display: none;">Delete Cover Image</a>
                                </div>
                                <div class="custom-file">
                                    <input type="file" accept="image/*" name="thumbnail" id="cover" class="custom-file-input js-upload-image form-control">
                                    <label class="custom-file-label " for="cover">Choose file</label>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer bg-whitesmoke">
                            <button type="submit" class="btn btn-simpan  btn-primary">
                                Simpan
                            </button>
                            <a href="{{route('posts.index')}}" class="btn btn-danger  btn-secondary">
                                Batal
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
      </section>
  </div>
@endsection

resources/views/admin/Post/edit.blade.php
@extends('admin_layout.view_stucture')
@section('Content')
<!-- Main Content -->
<div class="main-content">
    <section class="section">
        <div class="section-header">
            <h1>Edit Postingan</h1>
        </div>
        <form action="{{route('posts.update', $post->id)}}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('put')
            <div class="row">
                <div class="col-8">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="text-black-50">Posts</h4>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type="text" id="title" class="form-control @error('title') is-invalid @enderror"
                                    name="title" autofocus="" value="{{$post->title}}">
                                @error('title')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="title">Author</label>
                                <input type="text" id="title" class="form-control @error('author') is-invalid @enderror"
                                    name="author" autofocus="" value="{{Auth::user()->name}}">
                                @error('author')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="title">Author</label>
                                <select name="status" class="form-control" id="">
                                    @if ($post->status == 'Publish')
                                        <option value="Publish" class="form-control" selected>Publish</option>
                                        <option value="Draf" class="form-control">Draft</option>
                                        @else
                                        <option value="Draf" class="form-control" selected>Draft</option>
                                        <option value="Publish" class="form-control">Publish</option>
                                        
                                    @endif
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="description">isi</label>
                                <textarea id="isi" cols="30" rows="10"
                                    class="form-control @error('isi') is-invalid @enderror" style="height: auto;"
                                    name="isi">{{$post->isi}}</textarea>
                                @error('isi')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-4">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="text-black-50">Meta data</h4>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label>Gambar</label>
                                <div class="mb-2">
                                    <img src="" class="img-fluid" alt="" id="upload-img-preview" style="display: none;">
                                    <a href="#" class="text-danger" id="upload-img-delete" style="display: none;">Delete
                                        Cover Image</a>
                                </div>
                                <label>Gambar Sebelumnya</label>
                                <div class="mb-2">
                                    <img src="{{url($post->thumbnail)}}" class="img-fluid" alt=""
                                        style="display: block;">
                                </div>
                                <div class="custom-file">
                                    <input type="file" accept="image/*" name="thumbnail" id="cover"
                                        class="custom-file-input js-upload-image form-control">
                                    <label class="custom-file-label " for="cover">Choose file</label>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer bg-whitesmoke">
                            <button type="submit" class="btn btn-simpan  btn-primary">
                                Simpan
                            </button>

                            <a href="#" class="btn btn-danger  btn-secondary">
                                Batal
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </section>
</div>
@endsection

resources/views/admin/Post/index.blade.php
@extends('admin_layout.view_stucture')
@section('Content')
     <!-- Main Content -->
     <div class="main-content">
      <section class="section">
          <div class="section-header">
              <h1>Blog / Postingan</h1>
          </div>
          <div class="row">
            <div class="col">
              @if (session('status'))
                <div class="alert alert-success">
                    {{ session('status') }}
                </div>
              @endif
              <div class="card">
                <div class="card-body">
                <a href="{{route('posts.create')}}" class="btn btn-primary mt-2 mb-2 float-right">Add item</a>
                  <div class="table-responsive">
                    <table class="table table-bordered" width="100%" id="TABLE_POST">
                      <thead class="thead-light">
                        <tr>
                          <th class="thead">No</th>
                          <th class="thead">Judul</th>
                          <th class="thead">Thumbnail</th>
                          <th class="thead">Status</th>
                          <th class="thead">Aksi</th>
                        </tr>
                      </thead>
                        <tbody>
                          @foreach ($post as $item)  
                          <tr>
                            <td>{{$loop->iteration}}</td>
                            <td>{{$item->title}}</td>
                           <td><img src="{{url($item->thumbnail)}}" alt="" width="80px"></td>
                            <td>{{$item->status}}</td>
                            <td>
                              <form action="{{route('posts.destroy', $item->id)}}" method="POST" class="d-inline">
                                @csrf
                                @method('delete')
                                <button type="submit" class="btn btn-danger ml-2 mr-2 mt-1">Delete</button>
                              </form>
                              <a href="{{route('posts.edit', Crypt::Encrypt($item->id))}}" class="btn btn-success ml-2 mr-2 mt-1">Edit</a></td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
      </section>
  </div>
@endsection